rust-lang/rfcbot-rs

vagrant/native_deps.sh, vagrant/pg_hba.conf
Just some minor adjustments I had to make to get the vagrant box running.
- Git is required to be on the guest to install some of the bower dependencies
- IPv6 seems to get enabled at some point after rebooting the virtual machine, postgres's pg_hba.conf doesn't have any rules for IPv6's localhost
Other than that, everything ran as expected! I got the environment up and running on a Windows 10 machine, so if you wanted to stress how well your vagrant scripts are configured I can definitely say they work quite well!
I did hit some windows specific quirks relating to CRLF vs LF and symlinks, but these are environment problems so I'm not sure if documenting the solutions to them is in scope of this project.
=> Missing vagrant environment configurations

README.md, Vagrantfile, vagrant/frontend.sh, vagrant/native_deps.sh, vagrant/vagrant_env.sh
Some small tweaks to improve first time vagrant up experience
**Added POST_COMMENTS to vagrant_env.sh** 
Fixes freshly bootstraped vagrant boxes from failing to run the rust back end. The recent changes require POST_COMMENTS to be true or false before running the rust back end, but this is not included in vagrant_env.sh. I assume false is a sane default in this case.
**Created frontend provisioning script**
This script handles pulling in all of the frontend's dependencies. It also creates a symlink from the node_modules directory inside the shared /vagrant folder to the Vagrant VM's home folder. This fixes issues in windows where npm install tries to create symlinks in a NTFS backed file system. It also speeds up the npm install process as Virtual Box's shared folder engine is …
=> Vagrant Bootstrap Fixes

src/config.rs, src/github/client.rs, src/main.rs, src/scraper.rs
Previously, bootstrap would only get information for `rust-lang/rust` instead of all repos in `rust-lang`, `rust-lang-nursery` or `rust-lang-deprecated`. This PR refactors the scraping logic into its own function and re-uses that function during bootstrap.
=> Bootstrap all repos from Github

migrations/20170323184941_unique_issue_repo_number/down.sql, migrations/20170323184941_unique_issue_repo_number/up.sql, src/fix.rs, src/github/client.rs, src/github/mod.rs, src/main.rs
I added a new subcommand `fix`, that will search for all duplicate issues, delete them and their associated comments, and then rescrapes their data from Github. It's not super resistant to errors, but hopefully this is a one time thing 🙏.
I've also added a migration to create a unique index on `issue` so that this doesn't happen again.
The expected usage would be:
```
cargo run --release -- fix
diesel migration run
```
(Have confirmed it addresses the overcounting noted in https://github.com/dikaiosune/rust-dashboard/issues/114#issuecomment-283452665).
=> Remove duplicate issues

Cargo.lock, Cargo.toml, src/github/mod.rs, src/github/nag.rs, src/releases.rs, src/reports/mod.rs
I suspect that the "if not exists then insert" logic plus a race condition caused the duplicate issues we saw earlier. Luckily, Postgresql 9.5 and Diesel 0.12 are both the first version to support upserts.
This requires upgrading Diesel to 0.12 (which required upgrading Chrono to 0.3 and Serde to 0.9), but luckily we weren't using either extensively enough to have tons of breaking changes.
=> [WIP] Use upserts

src/github/webhooks.rs
Right now, https://rusty-dash.com/builds is empty, so something's clearly not working correctly.
The old logic was:
1. Get a status update from Github
2. If status says the build is finished and the commit is the `HEAD` of the `auto` branch, then process.
Without looking at the logs, I'm guessing that the problem is that:
1. @bors pushes a new commit to the `auto` branch
2. A build starts. We get a notification but ignore it (because the status is still `pending`)
3. The build finishes and @bors pushes overwrites onto the `auto` branch
4. We receive a status update that the build has finished, but because the commit has been overwritten on `auto`, we ignore it.
This assumes that somehow @bors overwrites the `auto` branch before the webhook notification gets sent out, so I'm not sure how …
=> Process build info for all commits from @bors

teams.toml
https://internals.rust-lang.org/t/welcome-kodraus-and-withoutboats-as-full-libs-team-members/6582
=> Add @KodrAus and @withoutboats to libs team

teams.toml
Removed @arielb1 and @jseyfried (https://github.com/rust-lang/rust/pull/46108#issuecomment-363152084).
Added @nagisa and @oli-obk (https://internals.rust-lang.org/t/please-welcome-nagisa-and-oli-obk-to-the-compiler-team/6712).
=> Update compiler team

src/github/nag.rs
Allows an item to enter FCP when a majority of team members has approved
and *no* team member has objected. This retains the consensus process,
but makes it so that FCP isn't blocked *by default*. Rather, members who
object to the proposal need to register a concern to block it.
=> Loosen FCP restrictions

.gitignore, rfcbot.toml, src/github/nag.rs, src/main.rs, src/teams.rs
See title.
This might not work right now due to `-> impl Trait`, in which case I'll need to bump the nightly version... ;)
=> Fix #201 (Controllable auto-close/postpone behavior)

rfcbot.toml
I renamed the rustdoc team label recently, to consolidate the three miscellaneous tags that were being used. This is me updating the rfcbot configuration to listen for the new tag.
=> rename rustdoc team label

src/domain/rfcbot.rs
Logic defined in https://github.com/anp/rfcbot-rs/blob/master/src/github/nag.rs#L824-L828 was interpreted as setting `fcp_start` to `NULL` (in the database), but didn't change anything.
Snippet:
```rust
proposal.fcp_start = None;
let update =
diesel::update(fcp_proposal.find(proposal.id))
.set(&proposal)
.execute(conn);
```
Per documentation in http://diesel.rs/guides/all-about-updates/, setting the following on `FcpProposal` should give us the behavior we wanted.
```rust
#[changeset_options(treat_none_as_null="true")]
```
At least that's the hope.
=> Attempt at solving #217 (diesel.rs docs were misinterpreted)

src/nag.rs
=> Fix #212 by filtering in RFCs not yet in FCP

rfcbot.toml
This PR updates T-infra team membership in rfcbot, to sync it with the people listed on the website.
cc @aidanhs
=> Update T-infra membership

src/github/nag.rs
I wasn't sure if you could mention more than one team or not.  If it's only one team then maybe it should say:
> review by the rest of the tagged team
But going for
> review by the rest of the tagged team members
allows for it to mean all the members of all the teams.
=> Correct FCP merge text

src/github/nag.rs
Thank you, @jethrogb, for the suggestion!
Fixes #258
=> Clarify what consensus/majority means

src/github/nag.rs
This is a quick-fix since the comment-author refers to the team member who FCPed.
See e.g. https://github.com/rust-lang/rfcs/pull/2532#issuecomment-466992905 for the bug.
We should fix this properly later, but this suffices for now and is all I have time for.
r? @anp
=> Refer to author indirectly

Cargo.lock, src/github/nag.rs
Example: https://github.com/rust-lang/rfcs/pull/2635#issuecomment-486362515
=> Determine if issue is PR to avoid refresh pages

src/github/nag.rs
These days, FCPs are most commonly used in contexts other than RFCs. Of the [17 currently open FCPs](https://rfcbot.rs), 3 are in `rust-lang/rfcs` and 14 are in other `rust-lang` repositories. Mostly rfcbot handles this fine, but it's a bit disconcerting that when it's closing an FCP it says "the RFC", even if the thing it's dealing with isn't one. Everywhere else, it just says "this", but for some reason the termination message is handedly differently. This PR updates the message to describe the thing being FCPed more neutrally.
=> Change FCP close message to allow for non-RFC FCPs

README.md
#211 updated the bot to parse multiple commands in the same comment and added a note about this to the readme, but did not remove the previous note saying this would not work, resulting in contradictory language.
=> resolve multiple commands confusion in readme

src/nag.rs
I'd really like to see RFCs in active final comment period that I haven't reviewed yet. Especially since now is my last chance to review them!
The current filter was originally added to address #212; I think this filter would have addressed that concern as well.
=> Continue showing active FCPs in individual nags

src/nag.rs
This helps a user prioritize their requests by seeing how close each of them is to being accepted.
=> Add count of reviews and concerns to /api/<username>
