rust-lang/rfcbot-rs

- front/app/templates/releases.hbs
> Configured template to only show (since <date>) if date object is not falsy

- front/app/index.html
- front/public/cgi-bin/printenv.sh
- front/public/humans.txt
> Add humans.txt and cgi-bin/printenv.sh

- front/app/styles/app.css
- front/app/templates/application.hbs
This makes the menu fixed to the top of your screen.
> Make menu fixed

- Cargo.lock
- Cargo.toml
- README.md
- Vagrantfile
- vagrant/native_deps.sh
- vagrant/postgres.sh
- vagrant/rust.sh
Also required updating Diesel and friends to `0.10`.
> Update bootstrap to use stable Rust

- src/github/client.rs
- src/github/models.rs
A bunch of small refactor-ings to the `github` module. Each commit is self-contained and independent, so hopefully it's not too hard to review.
> Simplify github code

- src/domain/github.rs
- src/github/mod.rs
- src/github/webhooks.rs
Continues #133 
Supercedes #134 (which I accidentally closed and now can't re-open because I force-pushed. Oops).
> More Upserts

- front/app/templates/fcp.hbs
Close https://github.com/dikaiosune/rust-dashboard/issues/139
> Display issue title on FCP page

- src/github/nag.rs
want to let CI pass first since i did this in the github editor
> Support either form of resolving a concern.

- migrations/2017080418520000_add_petrochenkov_compiler_team/down.sql
- migrations/2017080418520000_add_petrochenkov_compiler_team/up.sql
I've never done this before, so hopefully I did it right. =)
> add migration for moving petrochenkov to the compiler team

- .travis.yml
- Cargo.lock
- README.md
- src/domain/schema.rs
> build without requiring a local postgres

- migrations/2017110900000000_add_zoxc_compiler_team/down.sql
- migrations/2017110900000000_add_zoxc_compiler_team/up.sql
@Zoxc is joining the compiler team.
> migration: add Zoxc to the compiler team

- teams.toml
Gah sorry, forgot to remove myself also!
> Finish libs team update

- teams.toml
With the new fcp threshold, bring back kimundi
> reinstate kimundi on libs

- teams.toml
Let's add matklad back to the Cargo team so that he can finally propose an fcp @aturon was planing to propose ages ago? :-) 
r? @aturon
> Re-add matklad to Cargo team

- teams.toml
https://www.ncameron.org/blog/dev-tools-in-2018/#devtools
> new devtools team members

- teams.toml
And remove mw from the dev tools team
> Add rustdoc and IDEs teams

- rfcbot.toml
> Removing myself from teams I'm no longer on

- rfcbot.toml
So that we can approve https://github.com/rust-lang/rfcs/pull/2614 :)
> Add crates.io and moderation teams

- src/github/nag.rs
Closes https://github.com/anp/rfcbot-rs/issues/255.
Roughly based on @anp's suggestion but made to fit the existing information (i.e. link to review...).
> Improve the FCP completion message

- src/github/nag.rs
As observed in https://github.com/rust-lang/rfcs/pull/2627#issuecomment-466812235
> Fix typos in nag.rs

- .travis.yml
- rustfmt.toml
- src/config.rs
- src/domain/github.rs
- src/domain/rfcbot.rs
- src/domain/schema.rs
- src/error.rs
- src/github/client.rs
- src/github/command.rs
- src/github/mod.rs
- src/github/models.rs
- src/github/nag.rs
- src/github/webhooks.rs
- src/main.rs
- src/nag.rs
- src/scraper.rs
- src/server.rs
- src/teams.rs
- src/utils.rs
> Run cargo fmt on whole project 

- CONTRIBUTING.md
- src/github/nag.rs
> Correct links to rust-lang organization

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/github/webhooks.rs
Should help us diagnose webhook failures.
> Path to deserialization error

- src/nag.rs
> Fix unresolved_concerns count in individual API
